FROM ubuntu:24.04

RUN apt update \
&&  apt install -y \
    cmake \
    build-essential \
    checkinstall \
    zlib1g-dev \
    libssl-dev \
&& apt clean \
&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /mayo/build
COPY . /mayo
WORKDIR /mayo/build

# avx2 
RUN  cmake -DMAYO_BUILD_TYPE=avx2 -DENABLE_AESNI=ON .. \
&&  make

CMD ["tail", "-f", "/dev/null"]
